# Generated by Django 2.2.5 on 2020-03-29 20:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='topics',
            name='published_date',
            field=models.CharField(max_length=100),
        ),
    ]
