# Generated by Django 2.2.5 on 2020-03-29 22:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0003_auto_20200330_0518'),
    ]

    operations = [
        migrations.AddField(
            model_name='topics',
            name='top_news',
            field=models.CharField(max_length=8, null=True),
        ),
    ]
