# Generated by Django 2.2.5 on 2020-03-29 23:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0004_topics_top_news'),
    ]

    operations = [
        migrations.AlterField(
            model_name='topics',
            name='description',
            field=models.TextField(null=True),
        ),
    ]
