# Generated by Django 2.2.5 on 2020-03-30 05:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0005_auto_20200330_0846'),
    ]

    operations = [
        migrations.AlterField(
            model_name='topics',
            name='published_date',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='topics',
            name='title',
            field=models.CharField(max_length=400, null=True),
        ),
    ]
